org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC
android.useAndroidX=true
kotlin.incremental=false
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiaGFzaG5hdGUiLCJhIjoiY21vanFqZmhuMDFrNTJxc2IxdnNicTNtZyJ9.3nVHY2bg18Tc0qY9hwVaZQ
GOOGLE_MAPS_API_KEY=YOUR_GOOGLE_MAPS_API_KEY
