"""add_budget_name_and_status

Revision ID: c7ccdbe04d95
Revises: 27d7bd79da07
Create Date: 2026-04-28 16:41:52.160002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ccdbe04d95'
down_revision: Union[str, None] = '27d7bd79da07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('name', sa.String(length=100), nullable=False, server_default='My Budget'))
    op.add_column('budgets', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'is_active')
    op.drop_column('budgets', 'name')
    # ### end Alembic commands ###
