# The helper script location
flutter_ios_podfile_setup = File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'podhelper.rb')
require flutter_ios_podfile_setup

platform :ios, '14.0'

# CocoaPods analytics sends anonymous usage data to shared servers.
# If you don't want to send this data, or unless you're code signing,
# uncomment the following line.
# keep_message_log = false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
